# Generated by Django 5.0.4 on 2024-05-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_get_in_touch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_in_touch',
            options={'verbose_name_plural': 'Get in touch objects'},
        ),
    ]
