# Generated by Django 5.0.4 on 2024-05-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_get_in_touch_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
