# Generated by Django 5.0.6 on 2024-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
