# Generated by Django 5.0.6 on 2024-05-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plans',
            field=models.CharField(blank=True, choices=[('Sapa', 'Sapa'), ('Baller', 'Baller'), ('Working', 'Working')], max_length=100, null=True),
        ),
    ]
