# Generated by Django 5.0.6 on 2024-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pricingplan_pricing_alter_pricingplan_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='plans',
            field=models.CharField(blank=True, choices=[('Sapa Pricing', 'Sapa Pricing'), ('Baller Pricing', 'Baller Pricing'), ('9-5 Pricing', '9-5 Pricing')], max_length=100, null=True),
        ),
    ]
