# Generated by Django 5.1.3 on 2024-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_pricingplan_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('computer_appreciation', 'Computer Appreciation'), ('microsoft_word', 'Microsoft Word'), ('microsoft_excel', 'Microsoft Excel'), ('microsoft_access', 'Microsoft Access'), ('microsoft_powerpoint', 'Microsoft Powerpoint')], max_length=50)),
                ('education_level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary School'), ('university', 'University')], max_length=50)),
                ('teaching_method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('currently_in_school', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('secret_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Get_in_touch',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
